### PR TITLE
store display config in file and apply it

### PR DESCRIPTION
**Pull request by vtolstov**
Signed-off-by: Vasiliy Tolstov <v.tolstov@selfip.ru>

### CODE REVIEW

**Comment by marcelhollerbach** [comment]
Very very very cool! :)

**Comment by marcelhollerbach** [comment]
Just one minor thing after testing it.

If someone ,with a old config running, is starting verne with this patch he wont see file details or bookmarks, since the values will be 0 by that time.

What do you think of increasing the CONFIG_VERSION to 2.1 ? :)

**Comment by vtolstov** [comment]
2017-07-14 23:37 GMT+03:00 Marcel Hollerbach <notifications@github.com>:

> Just one minor thing after testing it.
>
> If someone ,with a old config running, is starting verne with this patch
> he wont see file details or bookmarks, since the values will be 0 by that
> time.
>
> What do you think of increasing the CONFIG_VERSION to 2.1 ? :)
>
> —
>

I think about it, but may be we go to first minimal release something like
0.0.1 or so and after that increase version?
I don't think that many users used this now...
What do you think?


-- 
Vasiliy Tolstov,
e-mail: v.tolstov@selfip.ru

**Comment by marcelhollerbach** [comment]
mhmm i would continue with increasing the minimum number, once i am doing a release i will change the name and start again at the first version :)

**Comment by vtolstov** [comment]
one moment, i'm try to invert logick.

**Comment by vtolstov** [comment]
what do you think now?
p.s. i can't test latest commit now

**Comment by marcelhollerbach** [comment]
mhmm it currently doesnt compile anymore, whats the problem with the latest commit ?

**Comment by marcelhollerbach** [comment]
Perfectly! Merged now, there was just one minor thing, nothing major, thank you alot! :)

**Pull request merged**
